apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-portal-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: job-portal-backend
  template:
    metadata:
      labels:
        app: job-portal-backend
    spec:
      containers:
      - name: backend
        image: job-portal-backend:latest
        ports:
        - containerPort: 5001
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: gemini-api-key

---
apiVersion: v1
kind: Service
metadata:
  name: job-portal-service
spec:
  selector:
    app: job-portal-backend
  ports:
  - port: 80
    targetPort: 5001
  type: LoadBalancer